### ISSUE TITLE
Question not an issue

### ISSUE THREAD

**Issue by honglili-qochealth** [jaredsburrows/android-gif-example#40]
Hi Jared,
How did you generate project-scheme.json under gradle folder?
I was facing a similar issue you had regarding "Unresolved reference: compile".

My build was working with gradle **4.0.2**,  but not any version after that.

Thanks,
HL

**Comment by jaredsburrows** [comment]
Try `gradlew kotlinDslAccessorsSnapshot`

**Comment by jaredsburrows** [comment]
@honglili-qochealth Did this help? If so, can we close this?

**Comment by honglili-qochealth** [comment]
Thanks, @jaredsburrows , I had a different issue.

**Comment by jaredsburrows** [comment]
@honglili-qochealth What is the different issue? Anything I can help with?

**Comment by jaredsburrows** [comment]
Ok. Nice!
