### ISSUE TITLE
Plugin unsupported on gradle 5.4.1

### ISSUE THREAD

**Issue by vyadav33e** [jaredsburrows/android-gif-example#97]
Log:
com.android.tools.idea.gradle.project.sync.ng.NewGradleSyncNotSupportedException: New Gradle Sync is not supported due to containing Kotlin modules using an unsupported plugin version

**Comment by jaredsburrows** [comment]
Updated Gradle to 5.5 and it syncs fine running Intellij 2019.1.2. Let me know if you still see problems!
